---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dfsf.dfdfdsfs
  description: ffdfdv
  tags:
    - ansible
    - collection
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: test-rhaap-1/sdfasdasdfs
  links:
    - url: https://devspaces.apps.ansible-rhdh-dev.testing.ansible.com/#https://github.com/test-rhaap-1/sdfasdasdfs
      title: Open Ansible project in OpenShift Dev Spaces
      icon: web
spec:
  type: collection-project
  system: dsdsdasd
  lifecycle: production
  owner: sdasda
